// Code generated by qtc from "simple.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//
// --------------------------------------------------------------------------------
//

//line templater/templates/simple.qtpl:6
package templates

//line templater/templates/simple.qtpl:6
import "hash/fnv"

//line templater/templates/simple.qtpl:7
import "fmt"

//line templater/templates/simple.qtpl:8
import "time"

//line templater/templates/simple.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templater/templates/simple.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templater/templates/simple.qtpl:11
// arbitrary Go code may be embedded here!

func hash(s string) string {
	h := fnv.New32a()
	h.Write([]byte(s))
	return fmt.Sprint(h.Sum32()) + fmt.Sprint(time.Now().Nanosecond())
}

type PostmanSimplePayload struct {
	Name               string
	Description        string
	RequestDirectories []struct {
		Name     string
		Requests []PostmanSimpleRequestMarkupDataV1
	}
}

type PostmanSimpleRequestMarkupDataV1 struct {
	Directory   string
	Name        string
	Description string
	HTTPVerb    string
	URL         string

	QueryParams []PostmanSimpleRequestQueryParam
	URLParams   []PostmanSimpleRequestURLParam

	ExampleRequestBody string
	Responses          []PostmanSimpleExampleResponse

	CURL string
}

type PostmanSimpleExampleResponse struct {
	Name         string
	Code         int
	Status       string
	ResponseBody string
}

type PostmanSimpleRequestQueryParam struct {
	Key         string
	Description string
	Sample      string
	Type        string
	Required    bool
}

type PostmanSimpleRequestURLParam struct {
	Name        string
	Description string
	Sample      string
	Type        string
	Required    bool
}

//line templater/templates/simple.qtpl:69
func StreamMakePostmanSimple(qw422016 *qt422016.Writer, p PostmanSimplePayload) {
//line templater/templates/simple.qtpl:69
	qw422016.N().S(`# `)
//line templater/templates/simple.qtpl:70
	qw422016.E().S(p.Name)
//line templater/templates/simple.qtpl:70
	qw422016.N().S(` {`)
//line templater/templates/simple.qtpl:70
	qw422016.E().S(hash(p.Name))
//line templater/templates/simple.qtpl:70
	qw422016.N().S(`}

`)
//line templater/templates/simple.qtpl:72
	if p.Description != "" {
//line templater/templates/simple.qtpl:73
		qw422016.E().S(p.Description)
//line templater/templates/simple.qtpl:74
	}
//line templater/templates/simple.qtpl:74
	qw422016.N().S(`


`)
//line templater/templates/simple.qtpl:77
	for _, dir := range p.RequestDirectories {
//line templater/templates/simple.qtpl:77
		qw422016.N().S(`## `)
//line templater/templates/simple.qtpl:78
		qw422016.E().S(dir.Name)
//line templater/templates/simple.qtpl:78
		qw422016.N().S(` {`)
//line templater/templates/simple.qtpl:78
		qw422016.E().S(hash(dir.Name))
//line templater/templates/simple.qtpl:78
		qw422016.N().S(`}

`)
//line templater/templates/simple.qtpl:80
		for _, req := range dir.Requests {
//line templater/templates/simple.qtpl:80
			qw422016.N().S(`### `)
//line templater/templates/simple.qtpl:81
			qw422016.E().S(req.Name)
//line templater/templates/simple.qtpl:81
			qw422016.N().S(` {`)
//line templater/templates/simple.qtpl:81
			qw422016.E().S(hash(req.Name))
//line templater/templates/simple.qtpl:81
			qw422016.N().S(`}

| | |
|--|--|
|__Name__| `)
//line templater/templates/simple.qtpl:85
			qw422016.E().S(req.Name)
//line templater/templates/simple.qtpl:85
			qw422016.N().S(`|
|__URL__| `)
//line templater/templates/simple.qtpl:86
			qw422016.E().S(req.URL)
//line templater/templates/simple.qtpl:86
			qw422016.N().S(` |
|__Method__| `)
//line templater/templates/simple.qtpl:87
			qw422016.E().S(req.HTTPVerb)
//line templater/templates/simple.qtpl:87
			qw422016.N().S(`|

`)
//line templater/templates/simple.qtpl:89
			if req.Description != "" {
//line templater/templates/simple.qtpl:89
				qw422016.N().S(`#### Description
`)
//line templater/templates/simple.qtpl:91
				qw422016.E().S(req.Description)
//line templater/templates/simple.qtpl:92
			}
//line templater/templates/simple.qtpl:92
			qw422016.N().S(`

#### Request
`)
//line templater/templates/simple.qtpl:95
			if req.CURL != "" {
//line templater/templates/simple.qtpl:95
				qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:95
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:95
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:95
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:95
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:95
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:95
				qw422016.N().S(`sh
`)
//line templater/templates/simple.qtpl:97
				qw422016.N().S(req.CURL)
//line templater/templates/simple.qtpl:97
				qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:97
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:97
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:97
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:97
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:97
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:97
				qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:99
			}
//line templater/templates/simple.qtpl:99
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:101
			if len(req.QueryParams) != 0 {
//line templater/templates/simple.qtpl:101
				qw422016.N().S(`
| Query Parameters | Value |
|-----|-------|
`)
//line templater/templates/simple.qtpl:105
				for _, qp := range req.QueryParams {
//line templater/templates/simple.qtpl:105
					qw422016.N().S(`| <span style="color:green">`)
//line templater/templates/simple.qtpl:106
					qw422016.E().S(qp.Key)
//line templater/templates/simple.qtpl:106
					qw422016.N().S(`</span> `)
//line templater/templates/simple.qtpl:106
					qw422016.E().S(qp.Type)
//line templater/templates/simple.qtpl:106
					if qp.Required {
//line templater/templates/simple.qtpl:106
						qw422016.N().S(``)
//line templater/templates/simple.qtpl:106
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:106
						qw422016.N().S(`required`)
//line templater/templates/simple.qtpl:106
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:106
					}
//line templater/templates/simple.qtpl:106
					qw422016.N().S(`| `)
//line templater/templates/simple.qtpl:106
					qw422016.E().S(qp.Description)
//line templater/templates/simple.qtpl:106
					qw422016.N().S(`|
`)
//line templater/templates/simple.qtpl:107
				}
//line templater/templates/simple.qtpl:108
			}
//line templater/templates/simple.qtpl:108
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:110
			if len(req.URLParams) != 0 {
//line templater/templates/simple.qtpl:110
				qw422016.N().S(`| URL Params | Description |
|-----|-------|
`)
//line templater/templates/simple.qtpl:113
				for _, up := range req.URLParams {
//line templater/templates/simple.qtpl:113
					qw422016.N().S(`| <span style="color:green">`)
//line templater/templates/simple.qtpl:114
					qw422016.E().S(up.Name)
//line templater/templates/simple.qtpl:114
					qw422016.N().S(`</span> `)
//line templater/templates/simple.qtpl:114
					qw422016.E().S(up.Type)
//line templater/templates/simple.qtpl:114
					if up.Required {
//line templater/templates/simple.qtpl:114
						qw422016.N().S(``)
//line templater/templates/simple.qtpl:114
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:114
						qw422016.N().S(`required`)
//line templater/templates/simple.qtpl:114
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:114
					}
//line templater/templates/simple.qtpl:114
					qw422016.N().S(`| `)
//line templater/templates/simple.qtpl:114
					qw422016.E().S(up.Description)
//line templater/templates/simple.qtpl:114
					qw422016.N().S(`|
`)
//line templater/templates/simple.qtpl:115
				}
//line templater/templates/simple.qtpl:116
			}
//line templater/templates/simple.qtpl:116
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:118
			if len(req.Responses) != 0 {
//line templater/templates/simple.qtpl:118
				qw422016.N().S(`#### Response Examples

`)
//line templater/templates/simple.qtpl:121
				for i, resp := range req.Responses {
//line templater/templates/simple.qtpl:121
					qw422016.N().S(`##### Example `)
//line templater/templates/simple.qtpl:122
					qw422016.N().D(i + 1)
//line templater/templates/simple.qtpl:122
					qw422016.N().S(`: `)
//line templater/templates/simple.qtpl:122
					qw422016.E().S(resp.Name)
//line templater/templates/simple.qtpl:122
					qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:122
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:122
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:122
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:122
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:122
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:122
					qw422016.N().S(`json
Code: `)
//line templater/templates/simple.qtpl:125
					qw422016.N().D(resp.Code)
//line templater/templates/simple.qtpl:125
					qw422016.N().S(` `)
//line templater/templates/simple.qtpl:125
					qw422016.N().S(resp.Status)
//line templater/templates/simple.qtpl:125
					qw422016.N().S(`
------------------------------------------
`)
//line templater/templates/simple.qtpl:127
					qw422016.N().S(resp.ResponseBody)
//line templater/templates/simple.qtpl:127
					qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:127
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:127
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:127
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:127
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:127
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:127
					qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:130
				}
//line templater/templates/simple.qtpl:131
			}
//line templater/templates/simple.qtpl:131
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:133
		}
//line templater/templates/simple.qtpl:134
	}
//line templater/templates/simple.qtpl:134
	qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:136
}

//line templater/templates/simple.qtpl:136
func WriteMakePostmanSimple(qq422016 qtio422016.Writer, p PostmanSimplePayload) {
//line templater/templates/simple.qtpl:136
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templater/templates/simple.qtpl:136
	StreamMakePostmanSimple(qw422016, p)
//line templater/templates/simple.qtpl:136
	qt422016.ReleaseWriter(qw422016)
//line templater/templates/simple.qtpl:136
}

//line templater/templates/simple.qtpl:136
func MakePostmanSimple(p PostmanSimplePayload) string {
//line templater/templates/simple.qtpl:136
	qb422016 := qt422016.AcquireByteBuffer()
//line templater/templates/simple.qtpl:136
	WriteMakePostmanSimple(qb422016, p)
//line templater/templates/simple.qtpl:136
	qs422016 := string(qb422016.B)
//line templater/templates/simple.qtpl:136
	qt422016.ReleaseByteBuffer(qb422016)
//line templater/templates/simple.qtpl:136
	return qs422016
//line templater/templates/simple.qtpl:136
}
