// Code generated by qtc from "simple.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//
// --------------------------------------------------------------------------------
//

//line templater/templates/simple.qtpl:6
package templates

//line templater/templates/simple.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templater/templates/simple.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templater/templates/simple.qtpl:7
// arbitrary Go code may be embedded here!

type PostmanSimplePayload struct {
	Name               string
	Description        string
	RequestDirectories []struct {
		Name     string
		Requests []PostmanSimpleRequestMarkupDataV1
	}
}

type PostmanSimpleRequestMarkupDataV1 struct {
	Directory   string
	Name        string
	Description string
	HTTPVerb    string
	URL         string

	QueryParams []PostmanSimpleRequestQueryParam
	URLParams   []PostmanSimpleRequestURLParam

	ExampleRequestBody string
	Responses          []PostmanSimpleExampleResponse

	CURL string
}

type PostmanSimpleExampleResponse struct {
	Name         string
	Code         int
	Status       string
	ResponseBody string
}

type PostmanSimpleRequestQueryParam struct {
	Key         string
	Description string
	Sample      string
	Type        string
	Required    bool
}

type PostmanSimpleRequestURLParam struct {
	Name        string
	Description string
	Sample      string
	Type        string
	Required    bool
}

//line templater/templates/simple.qtpl:59
func StreamMakePostmanSimple(qw422016 *qt422016.Writer, p PostmanSimplePayload) {
//line templater/templates/simple.qtpl:59
	qw422016.N().S(`# `)
//line templater/templates/simple.qtpl:60
	qw422016.E().S(p.Name)
//line templater/templates/simple.qtpl:60
	qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:62
	if p.Description != "" {
//line templater/templates/simple.qtpl:63
		qw422016.E().S(p.Description)
//line templater/templates/simple.qtpl:64
	}
//line templater/templates/simple.qtpl:64
	qw422016.N().S(`


`)
//line templater/templates/simple.qtpl:67
	for _, dir := range p.RequestDirectories {
//line templater/templates/simple.qtpl:67
		qw422016.N().S(`## `)
//line templater/templates/simple.qtpl:68
		qw422016.E().S(dir.Name)
//line templater/templates/simple.qtpl:68
		qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:70
		for _, req := range dir.Requests {
//line templater/templates/simple.qtpl:70
			qw422016.N().S(`### `)
//line templater/templates/simple.qtpl:71
			qw422016.E().S(req.Name)
//line templater/templates/simple.qtpl:71
			qw422016.N().S(`

| | |
|--|--|
|__Name__| `)
//line templater/templates/simple.qtpl:75
			qw422016.E().S(req.Name)
//line templater/templates/simple.qtpl:75
			qw422016.N().S(`|
|__URL__| `)
//line templater/templates/simple.qtpl:76
			qw422016.E().S(req.URL)
//line templater/templates/simple.qtpl:76
			qw422016.N().S(` |
|__Method__| `)
//line templater/templates/simple.qtpl:77
			qw422016.E().S(req.HTTPVerb)
//line templater/templates/simple.qtpl:77
			qw422016.N().S(`|

`)
//line templater/templates/simple.qtpl:79
			if req.Description != "" {
//line templater/templates/simple.qtpl:79
				qw422016.N().S(`#### Description
`)
//line templater/templates/simple.qtpl:81
				qw422016.E().S(req.Description)
//line templater/templates/simple.qtpl:82
			}
//line templater/templates/simple.qtpl:82
			qw422016.N().S(`

#### Request
`)
//line templater/templates/simple.qtpl:85
			if req.CURL != "" {
//line templater/templates/simple.qtpl:85
				qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:85
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:85
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:85
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:85
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:85
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:85
				qw422016.N().S(`sh
`)
//line templater/templates/simple.qtpl:87
				qw422016.N().S(req.CURL)
//line templater/templates/simple.qtpl:87
				qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:87
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:87
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:87
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:87
				qw422016.N().S(``)
//line templater/templates/simple.qtpl:87
				qw422016.N().S("`")
//line templater/templates/simple.qtpl:87
				qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:89
			}
//line templater/templates/simple.qtpl:89
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:91
			if len(req.QueryParams) != 0 {
//line templater/templates/simple.qtpl:91
				qw422016.N().S(`
| Query Parameters | Value |
|-----|-------|
`)
//line templater/templates/simple.qtpl:95
				for _, qp := range req.QueryParams {
//line templater/templates/simple.qtpl:95
					qw422016.N().S(`| <span style="color:green">`)
//line templater/templates/simple.qtpl:96
					qw422016.E().S(qp.Key)
//line templater/templates/simple.qtpl:96
					qw422016.N().S(`</span> `)
//line templater/templates/simple.qtpl:96
					qw422016.E().S(qp.Type)
//line templater/templates/simple.qtpl:96
					if qp.Required {
//line templater/templates/simple.qtpl:96
						qw422016.N().S(``)
//line templater/templates/simple.qtpl:96
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:96
						qw422016.N().S(`required`)
//line templater/templates/simple.qtpl:96
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:96
					}
//line templater/templates/simple.qtpl:96
					qw422016.N().S(`| `)
//line templater/templates/simple.qtpl:96
					qw422016.E().S(qp.Description)
//line templater/templates/simple.qtpl:96
					qw422016.N().S(`|
`)
//line templater/templates/simple.qtpl:97
				}
//line templater/templates/simple.qtpl:98
			}
//line templater/templates/simple.qtpl:98
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:100
			if len(req.URLParams) != 0 {
//line templater/templates/simple.qtpl:100
				qw422016.N().S(`| URL Params | Description |
|-----|-------|
`)
//line templater/templates/simple.qtpl:103
				for _, up := range req.URLParams {
//line templater/templates/simple.qtpl:103
					qw422016.N().S(`| <span style="color:green">`)
//line templater/templates/simple.qtpl:104
					qw422016.E().S(up.Name)
//line templater/templates/simple.qtpl:104
					qw422016.N().S(`</span> `)
//line templater/templates/simple.qtpl:104
					qw422016.E().S(up.Type)
//line templater/templates/simple.qtpl:104
					if up.Required {
//line templater/templates/simple.qtpl:104
						qw422016.N().S(``)
//line templater/templates/simple.qtpl:104
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:104
						qw422016.N().S(`required`)
//line templater/templates/simple.qtpl:104
						qw422016.N().S("`")
//line templater/templates/simple.qtpl:104
					}
//line templater/templates/simple.qtpl:104
					qw422016.N().S(`| `)
//line templater/templates/simple.qtpl:104
					qw422016.E().S(up.Description)
//line templater/templates/simple.qtpl:104
					qw422016.N().S(`|
`)
//line templater/templates/simple.qtpl:105
				}
//line templater/templates/simple.qtpl:106
			}
//line templater/templates/simple.qtpl:106
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:108
			if len(req.Responses) != 0 {
//line templater/templates/simple.qtpl:108
				qw422016.N().S(`#### Response Examples

`)
//line templater/templates/simple.qtpl:111
				for i, resp := range req.Responses {
//line templater/templates/simple.qtpl:111
					qw422016.N().S(`##### Example `)
//line templater/templates/simple.qtpl:112
					qw422016.N().D(i + 1)
//line templater/templates/simple.qtpl:112
					qw422016.N().S(`: `)
//line templater/templates/simple.qtpl:112
					qw422016.E().S(resp.Name)
//line templater/templates/simple.qtpl:112
					qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:112
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:112
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:112
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:112
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:112
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:112
					qw422016.N().S(`json
Code: `)
//line templater/templates/simple.qtpl:115
					qw422016.N().D(resp.Code)
//line templater/templates/simple.qtpl:115
					qw422016.N().S(` `)
//line templater/templates/simple.qtpl:115
					qw422016.N().S(resp.Status)
//line templater/templates/simple.qtpl:115
					qw422016.N().S(`
------------------------------------------
`)
//line templater/templates/simple.qtpl:117
					qw422016.N().S(resp.ResponseBody)
//line templater/templates/simple.qtpl:117
					qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:117
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:117
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:117
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:117
					qw422016.N().S(``)
//line templater/templates/simple.qtpl:117
					qw422016.N().S("`")
//line templater/templates/simple.qtpl:117
					qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:120
				}
//line templater/templates/simple.qtpl:121
			}
//line templater/templates/simple.qtpl:121
			qw422016.N().S(`
`)
//line templater/templates/simple.qtpl:123
		}
//line templater/templates/simple.qtpl:124
	}
//line templater/templates/simple.qtpl:124
	qw422016.N().S(`

`)
//line templater/templates/simple.qtpl:126
}

//line templater/templates/simple.qtpl:126
func WriteMakePostmanSimple(qq422016 qtio422016.Writer, p PostmanSimplePayload) {
//line templater/templates/simple.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templater/templates/simple.qtpl:126
	StreamMakePostmanSimple(qw422016, p)
//line templater/templates/simple.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line templater/templates/simple.qtpl:126
}

//line templater/templates/simple.qtpl:126
func MakePostmanSimple(p PostmanSimplePayload) string {
//line templater/templates/simple.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
//line templater/templates/simple.qtpl:126
	WriteMakePostmanSimple(qb422016, p)
//line templater/templates/simple.qtpl:126
	qs422016 := string(qb422016.B)
//line templater/templates/simple.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
//line templater/templates/simple.qtpl:126
	return qs422016
//line templater/templates/simple.qtpl:126
}
